- name: Muestra variable usuario
  debug:
    msg: "user es: {{ plenv.user }}, os family es {{ ansible_os_family }}, distro es {{ ansible_distribution }} "

- include: "{{role_path}}/tasks/redhat.yml"
  when: ansible_os_family == 'RedHat'

- include: "{{role_path}}/tasks/debian.yml"
  when: ansible_os_family == 'Debian'

- name: Adds user if not exists
  user:
    name: "{{ plenv.user }}"

- name: Get Home Directory
  getent:
    database: passwd
    key: "{{ plenv.user }}"
    split: ":"
  become: yes

- name: exist plenv
  stat: path="{{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv"
  register: exist_plenv
  become: yes
  become_user: "{{ plenv.user }}"
  changed_when: false

- name: install plenv
  when: not exist_plenv.stat.exists
  git: repo={{ plenv.url }} dest={{ getent_passwd[plenv.user][4] }}/.plenv clone=yes
  become: yes
  become_user: "{{ plenv.user }}"

- name: exist perl build
  stat: path={{ getent_passwd[plenv.user][4] }}/.plenv/plugins/perl-build
  register: exist_perl_build
  become: yes
  become_user: "{{ plenv.user }}"
  changed_when: false

- name: install perl build
  when: not exist_perl_build.stat.exists
  git: repo={{ perl_build.url }} dest="{{ getent_passwd[plenv.user][4] }}/.plenv/plugins/perl-build" clone=yes
  become: yes
  become_user: "{{ plenv.user }}"

- name: set profile.d
  template: src=plenv.sh.j2 dest=/etc/profile.d/plenv.sh owner="{{ plenv.user }}" mode=744
  become: yes

- name: exist version
  shell: "{{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv versions | grep {{ plenv.local }} | wc -l"
  register: exist_version
  become: yes
  become_user: "{{ plenv.user }}"
  changed_when: false

- name: install perl
  when: exist_version.stdout == "0"
  shell: "{{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv install {{ plenv_perl_flags }} {{ plenv.local }}"
  become: yes
  become_user: "{{ plenv.user }}"

- name: "check local version"
  shell: "{{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv local | grep {{ plenv.local }} | wc -l"
  args:
    chdir: "{{ getent_passwd[plenv.user][4] }}/"
  register: check_version
  become: yes
  become_user: "{{ plenv.user }}"
  changed_when: false

- name: "set local perl"
  shell: "{{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv local {{ plenv.local }} && {{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv global {{ plenv.local }} && {{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv rehash"
  args:
    chdir: "{{ getent_passwd[plenv.user][4] }}/"
  become: yes
  become_user: "{{ plenv.user }}"
  when: check_version.stdout != "1"

- name: exist cpanm
  stat: path={{ getent_passwd[plenv.user][4] }}/.plenv/versions/{{ plenv.local }}/bin/cpanm
  register: exist_cpanm
  become: yes
  become_user: "{{ plenv.user }}"
  changed_when: false

- name: install cpanm
  shell: "{{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv install-cpanm && {{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv exec cpanm Carton && {{ getent_passwd[plenv.user][4] }}/.plenv/bin/plenv rehash"
  args:
    chdir: "{{ getent_passwd[plenv.user][4] }}/"
  become: yes
  become_user: "{{ plenv.user }}"
  when: not exist_cpanm.stat.exists